// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#include "NativeSignupMsg.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeSignupMsg::NativeSignupMsg() = default;

NativeSignupMsg::~NativeSignupMsg() = default;

auto NativeSignupMsg::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeSignupMsg>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.username)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.password)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.phoneNumber)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.email)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.extra)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeSignupMsg::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 6);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeSignupMsg>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mUsername)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mPassword)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mPhoneNumber)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mEmail)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mExtra))};
}

}  // namespace djinni_generated
