// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#include "NativeLoginMsg.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeLoginMsg::NativeLoginMsg() = default;

NativeLoginMsg::~NativeLoginMsg() = default;

auto NativeLoginMsg::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeLoginMsg>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.account)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.password)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeLoginMsg::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 3);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeLoginMsg>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mAccount)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mPassword))};
}

}  // namespace djinni_generated
