// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#pragma once

#include "account_info.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeAccountInfo final {
public:
    using CppType = ::account_djinni::AccountInfo;
    using JniType = jobject;

    using Boxed = NativeAccountInfo;

    ~NativeAccountInfo();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeAccountInfo();
    friend ::djinni::JniClass<NativeAccountInfo>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/vell/chat/account/AccountInfo") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/vell/chat/account/TokenMsg;)V") };
    const jfieldID field_mUsername { ::djinni::jniGetFieldID(clazz.get(), "mUsername", "Ljava/lang/String;") };
    const jfieldID field_mPhoneNumber { ::djinni::jniGetFieldID(clazz.get(), "mPhoneNumber", "Ljava/lang/String;") };
    const jfieldID field_mEmail { ::djinni::jniGetFieldID(clazz.get(), "mEmail", "Ljava/lang/String;") };
    const jfieldID field_mExtra { ::djinni::jniGetFieldID(clazz.get(), "mExtra", "Ljava/lang/String;") };
    const jfieldID field_mToken { ::djinni::jniGetFieldID(clazz.get(), "mToken", "Lcom/vell/chat/account/TokenMsg;") };
};

}  // namespace djinni_generated
