// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#include "NativeAccountInfo.hpp"  // my header
#include "Marshal.hpp"
#include "NativeTokenMsg.hpp"

namespace djinni_generated {

NativeAccountInfo::NativeAccountInfo() = default;

NativeAccountInfo::~NativeAccountInfo() = default;

auto NativeAccountInfo::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeAccountInfo>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.username)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.password)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.phoneNumber)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.email)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.extra)),
                                                           ::djinni::get(::djinni_generated::NativeTokenMsg::fromCpp(jniEnv, c.token)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeAccountInfo::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 7);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeAccountInfo>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mUsername)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mPassword)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mPhoneNumber)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mEmail)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mExtra)),
            ::djinni_generated::NativeTokenMsg::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mToken))};
}

}  // namespace djinni_generated
