// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#pragma once

#include "djinni_support.hpp"
#include "token_msg.hpp"

namespace djinni_generated {

class NativeTokenMsg final {
public:
    using CppType = ::account_djinni::TokenMsg;
    using JniType = jobject;

    using Boxed = NativeTokenMsg;

    ~NativeTokenMsg();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeTokenMsg();
    friend ::djinni::JniClass<NativeTokenMsg>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/vell/chat/account/TokenMsg") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;ILjava/lang/String;)V") };
    const jfieldID field_mToken { ::djinni::jniGetFieldID(clazz.get(), "mToken", "Ljava/lang/String;") };
    const jfieldID field_mExpirationTimeSec { ::djinni::jniGetFieldID(clazz.get(), "mExpirationTimeSec", "I") };
    const jfieldID field_mUsername { ::djinni::jniGetFieldID(clazz.get(), "mUsername", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
