// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#pragma once

#include "djinni_support.hpp"
#include "refresh_token_msg.hpp"

namespace djinni_generated {

class NativeRefreshTokenMsg final {
public:
    using CppType = ::account_djinni::RefreshTokenMsg;
    using JniType = jobject;

    using Boxed = NativeRefreshTokenMsg;

    ~NativeRefreshTokenMsg();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeRefreshTokenMsg();
    friend ::djinni::JniClass<NativeRefreshTokenMsg>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/vell/chat/account/RefreshTokenMsg") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;ILjava/lang/String;)V") };
    const jfieldID field_mRefreshToken { ::djinni::jniGetFieldID(clazz.get(), "mRefreshToken", "Ljava/lang/String;") };
    const jfieldID field_mExpirationTimeSec { ::djinni::jniGetFieldID(clazz.get(), "mExpirationTimeSec", "I") };
    const jfieldID field_mUsername { ::djinni::jniGetFieldID(clazz.get(), "mUsername", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
