// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#pragma once

#include "account_resp.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeAccountResp final {
public:
    using CppType = ::account_djinni::AccountResp;
    using JniType = jobject;

    using Boxed = NativeAccountResp;

    ~NativeAccountResp();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeAccountResp();
    friend ::djinni::JniClass<NativeAccountResp>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/vell/chat/account/AccountResp") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V") };
    const jfieldID field_mCode { ::djinni::jniGetFieldID(clazz.get(), "mCode", "I") };
    const jfieldID field_mMsg { ::djinni::jniGetFieldID(clazz.get(), "mMsg", "Ljava/lang/String;") };
    const jfieldID field_mToken { ::djinni::jniGetFieldID(clazz.get(), "mToken", "Ljava/lang/String;") };
    const jfieldID field_mExtra { ::djinni::jniGetFieldID(clazz.get(), "mExtra", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
