// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#include "NativeAccountListener.hpp"  // my header
#include "NativeAccountResp.hpp"

namespace djinni_generated {

NativeAccountListener::NativeAccountListener() : ::djinni::JniInterface<::account::AccountListener, NativeAccountListener>() {}

NativeAccountListener::~NativeAccountListener() = default;

NativeAccountListener::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeAccountListener::JavaProxy::~JavaProxy() = default;

void NativeAccountListener::JavaProxy::on_signup_callback(const ::account::AccountResp & c_callback) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeAccountListener>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onSignupCallback,
                           ::djinni::get(::djinni_generated::NativeAccountResp::fromCpp(jniEnv, c_callback)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeAccountListener::JavaProxy::on_login_callback(const ::account::AccountResp & c_callback) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeAccountListener>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onLoginCallback,
                           ::djinni::get(::djinni_generated::NativeAccountResp::fromCpp(jniEnv, c_callback)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeAccountListener::JavaProxy::on_logout_callback(const ::account::AccountResp & c_callback) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeAccountListener>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onLogoutCallback,
                           ::djinni::get(::djinni_generated::NativeAccountResp::fromCpp(jniEnv, c_callback)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeAccountListener::JavaProxy::on_is_alive_callback(const ::account::AccountResp & c_callback) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeAccountListener>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onIsAliveCallback,
                           ::djinni::get(::djinni_generated::NativeAccountResp::fromCpp(jniEnv, c_callback)));
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
