// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#pragma once

#include "account_interface.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeAccountInterface final : ::djinni::JniInterface<::account::AccountInterface, NativeAccountInterface> {
public:
    using CppType = std::shared_ptr<::account::AccountInterface>;
    using CppOptType = std::shared_ptr<::account::AccountInterface>;
    using JniType = jobject;

    using Boxed = NativeAccountInterface;

    ~NativeAccountInterface();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeAccountInterface>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeAccountInterface>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeAccountInterface();
    friend ::djinni::JniClass<NativeAccountInterface>;
    friend ::djinni::JniInterface<::account::AccountInterface, NativeAccountInterface>;

};

}  // namespace djinni_generated
