// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

package com.vell.chat.account;

public abstract class AccountListener {
    public abstract void onSignupCallback(AccountResp callback);

    public abstract void onLoginCallback(AccountResp callback);

    public abstract void onLogoutCallback(AccountResp callback);

    public abstract void onIsAliveCallback(AccountResp callback);
}
