// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

package com.vell.chat.account;

/** 账号结果返回 */
public final class AccountResp {


    /*package*/ final int mCode;

    /*package*/ final String mMsg;

    /*package*/ final String mToken;

    /*package*/ final String mExtra;

    public AccountResp(
            int code,
            String msg,
            String token,
            String extra) {
        this.mCode = code;
        this.mMsg = msg;
        this.mToken = token;
        this.mExtra = extra;
    }

    public int getCode() {
        return mCode;
    }

    /** 错误码 */
    public String getMsg() {
        return mMsg;
    }

    public String getToken() {
        return mToken;
    }

    public String getExtra() {
        return mExtra;
    }

    @Override
    public String toString() {
        return "AccountResp{" +
                "mCode=" + mCode +
                "," + "mMsg=" + mMsg +
                "," + "mToken=" + mToken +
                "," + "mExtra=" + mExtra +
        "}";
    }

}
