// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

package com.vell.chat.account;

/** 全局事件监听 */
public abstract class AccountListener {
    public abstract void onSignupCallback(AccountResp callback, int seqId, AccountInfo info);

    public abstract void onLoginCallback(AccountResp callback, int seqId, AccountInfo info);

    public abstract void onLogoutCallback(AccountResp callback, int seqId);

    public abstract void onIsAliveCallback(AccountResp callback);
}
