// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

package com.vell.chat.account;

/** 所有账号相关信息，用于持久化到本地 */
public final class AccountInfo {


    /*package*/ final String mUsername;

    /*package*/ final String mPassword;

    /*package*/ final String mPhoneNumber;

    /*package*/ final String mEmail;

    /*package*/ final String mExtra;

    /*package*/ final TokenMsg mToken;

    public AccountInfo(
            String username,
            String password,
            String phoneNumber,
            String email,
            String extra,
            TokenMsg token) {
        this.mUsername = username;
        this.mPassword = password;
        this.mPhoneNumber = phoneNumber;
        this.mEmail = email;
        this.mExtra = extra;
        this.mToken = token;
    }

    public String getUsername() {
        return mUsername;
    }

    /** 用户名，唯一存在 */
    public String getPassword() {
        return mPassword;
    }

    public String getPhoneNumber() {
        return mPhoneNumber;
    }

    public String getEmail() {
        return mEmail;
    }

    public String getExtra() {
        return mExtra;
    }

    public TokenMsg getToken() {
        return mToken;
    }

    @Override
    public String toString() {
        return "AccountInfo{" +
                "mUsername=" + mUsername +
                "," + "mPassword=" + mPassword +
                "," + "mPhoneNumber=" + mPhoneNumber +
                "," + "mEmail=" + mEmail +
                "," + "mExtra=" + mExtra +
                "," + "mToken=" + mToken +
        "}";
    }

}
