// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

package com.vell.chat.account;

/** 登陆信息 */
public final class LoginMsg {


    /*package*/ final String mAccount;

    /*package*/ final String mPassword;

    public LoginMsg(
            String account,
            String password) {
        this.mAccount = account;
        this.mPassword = password;
    }

    public String getAccount() {
        return mAccount;
    }

    /** 账号，可以是用户名、手机号、email */
    public String getPassword() {
        return mPassword;
    }

    @Override
    public String toString() {
        return "LoginMsg{" +
                "mAccount=" + mAccount +
                "," + "mPassword=" + mPassword +
        "}";
    }

}
