// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

package com.vell.chat.account;

/** refresh_token信息 */
public final class RefreshTokenMsg {


    /*package*/ final String mRefreshToken;

    /*package*/ final int mExpirationTimeSec;

    /*package*/ final String mUsername;

    public RefreshTokenMsg(
            String refreshToken,
            int expirationTimeSec,
            String username) {
        this.mRefreshToken = refreshToken;
        this.mExpirationTimeSec = expirationTimeSec;
        this.mUsername = username;
    }

    public String getRefreshToken() {
        return mRefreshToken;
    }

    public int getExpirationTimeSec() {
        return mExpirationTimeSec;
    }

    public String getUsername() {
        return mUsername;
    }

    @Override
    public String toString() {
        return "RefreshTokenMsg{" +
                "mRefreshToken=" + mRefreshToken +
                "," + "mExpirationTimeSec=" + mExpirationTimeSec +
                "," + "mUsername=" + mUsername +
        "}";
    }

}
