// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

package com.vell.chat.account;

/** 注册信息 */
public final class SignupMsg {


    /*package*/ final String mUsername;

    /*package*/ final String mPassword;

    /*package*/ final String mPhoneNumber;

    /*package*/ final String mEmail;

    /*package*/ final String mExtra;

    public SignupMsg(
            String username,
            String password,
            String phoneNumber,
            String email,
            String extra) {
        this.mUsername = username;
        this.mPassword = password;
        this.mPhoneNumber = phoneNumber;
        this.mEmail = email;
        this.mExtra = extra;
    }

    public String getUsername() {
        return mUsername;
    }

    /** 用户名，唯一存在 */
    public String getPassword() {
        return mPassword;
    }

    public String getPhoneNumber() {
        return mPhoneNumber;
    }

    public String getEmail() {
        return mEmail;
    }

    public String getExtra() {
        return mExtra;
    }

    @Override
    public String toString() {
        return "SignupMsg{" +
                "mUsername=" + mUsername +
                "," + "mPassword=" + mPassword +
                "," + "mPhoneNumber=" + mPhoneNumber +
                "," + "mEmail=" + mEmail +
                "," + "mExtra=" + mExtra +
        "}";
    }

}
