// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

package com.vell.chat.account;

/** token信息 */
public final class TokenMsg {


    /*package*/ final String mToken;

    /*package*/ final int mExpirationTimeSec;

    /*package*/ final String mUsername;

    public TokenMsg(
            String token,
            int expirationTimeSec,
            String username) {
        this.mToken = token;
        this.mExpirationTimeSec = expirationTimeSec;
        this.mUsername = username;
    }

    public String getToken() {
        return mToken;
    }

    public int getExpirationTimeSec() {
        return mExpirationTimeSec;
    }

    public String getUsername() {
        return mUsername;
    }

    @Override
    public String toString() {
        return "TokenMsg{" +
                "mToken=" + mToken +
                "," + "mExpirationTimeSec=" + mExpirationTimeSec +
                "," + "mUsername=" + mUsername +
        "}";
    }

}
