// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

package com.vell.chat.account;

/** token信息 */
public final class TokenMsg {


    /*package*/ final String mToken;

    public TokenMsg(
            String token) {
        this.mToken = token;
    }

    public String getToken() {
        return mToken;
    }

    @Override
    public String toString() {
        return "TokenMsg{" +
                "mToken=" + mToken +
        "}";
    }

}
