load('@bazel_tools//tools/build_defs/repo:git.bzl', 'git_repository', 'new_git_repository')
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# grpc依赖
http_archive(
    name = "com_github_grpc_grpc",
    urls = [
        "https://github.com/grpc/grpc/archive/acd79569bff44550c87e09768e2184e91c7eb610.tar.gz",
    ],
    strip_prefix = "grpc-acd79569bff44550c87e09768e2184e91c7eb610",
    sha256 = "f5bb5ee99fb877ecb915773ac7f5a6e62cee9ce89731cccc779b0b5eb2cacfbf",
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()

load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")

grpc_extra_deps()

# glog依赖
http_archive(
    name = "com_github_gflags_gflags",
    strip_prefix = "gflags-2.2.2",
    urls = [
        "https://mirror.bazel.build/github.com/gflags/gflags/archive/v2.2.2.tar.gz",
        "https://github.com/gflags/gflags/archive/v2.2.2.tar.gz",
    ],
)

http_archive(
    name = "com_github_google_glog",
    urls = [
        "https://github.com/google/glog/archive/v0.4.0.tar.gz",
    ],
    strip_prefix = "glog-0.4.0",
    sha256 = "f28359aeba12f30d73d9e4711ef356dc842886968112162bc73002645139c39c",
)

# jsoncpp
http_archive(
    name = "com_github_cschuet_jsoncpp",
    strip_prefix = "jsoncpp-e1c68e5ceed5ed7b103aee853d1aac8900e06cce",
    urls = [
        "https://github.com/cschuet/jsoncpp/archive/e1c68e5ceed5ed7b103aee853d1aac8900e06cce.tar.gz",
    ],
)

load("@com_github_cschuet_jsoncpp//:bazel/repositories.bzl", "repositories")

repositories()

# hiredis
http_archive(
    name = "com_github_redis_hiredis",
    strip_prefix = "hiredis-0.14.0",
    urls = [
        "https://github.com/redis/hiredis/archive/v0.14.0.tar.gz",
    ],
    build_file = "//:libs/hiredis/hiredis.BUILD",
)