load('@bazel_tools//tools/build_defs/repo:git.bzl', 'git_repository', 'new_git_repository')
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_github_grpc_grpc",
    urls = [
        "https://github.com/grpc/grpc/archive/acd79569bff44550c87e09768e2184e91c7eb610.tar.gz",
    ],
    strip_prefix = "grpc-acd79569bff44550c87e09768e2184e91c7eb610",
    sha256 = "f5bb5ee99fb877ecb915773ac7f5a6e62cee9ce89731cccc779b0b5eb2cacfbf",
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()

load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")

grpc_extra_deps()