// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#pragma once

#include <cstdint>
#include <string>
#include <utility>

namespace account_djinni {

/** 账号结果返回 */
struct AccountResp final {
    int32_t code;
    /** 错误码 */
    std::string msg;
    std::string token;
    std::string extra;

    AccountResp(int32_t code_,
                std::string msg_,
                std::string token_,
                std::string extra_)
    : code(std::move(code_))
    , msg(std::move(msg_))
    , token(std::move(token_))
    , extra(std::move(extra_))
    {}
};

}  // namespace account_djinni
