// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#pragma once

namespace account_djinni {

struct AccountResp;

class AccountListener {
public:
    virtual ~AccountListener() {}

    virtual void on_signup_callback(const AccountResp & callback) = 0;

    virtual void on_login_callback(const AccountResp & callback) = 0;

    virtual void on_logout_callback(const AccountResp & callback) = 0;

    virtual void on_is_alive_callback(const AccountResp & callback) = 0;
};

}  // namespace account_djinni
