// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#pragma once

#include <cstdint>
#include <memory>

namespace account_djinni {

class AccountListener;
struct AccountInfo;
struct LoginMsg;
struct SignupMsg;

class AccountInterface {
public:
    virtual ~AccountInterface() {}

    /** 单例 */
    static std::shared_ptr<AccountInterface> get_instance();

    /** 初始化 */
    virtual void init() = 0;

    /** 全局事件监听 */
    virtual void add_listener(const std::shared_ptr<AccountListener> & listener) = 0;

    virtual void remove_listener(const std::shared_ptr<AccountListener> & listener) = 0;

    virtual void signup(const SignupMsg & info, int32_t seqId) = 0;

    /** seqId 函数请求id，在account_listener里callback */
    virtual void login(const LoginMsg & info, int32_t seqId) = 0;

    virtual void logout(int32_t seqId) = 0;

    virtual AccountInfo getAccountInfo() = 0;

    /** 手动发起服务器是否在线检查，会异步定时检查 */
    virtual void is_alive() = 0;

    /** 是否已经登录 */
    virtual bool has_login() = 0;
};

}  // namespace account_djinni
