// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#pragma once

#include <memory>

namespace account {

class AccountListener;
struct LoginMsg;
struct SignupMsg;
struct TokenMsg;

class AccountInterface {
public:
    virtual ~AccountInterface() {}

    static std::shared_ptr<AccountInterface> get_instance();

    virtual void add_listener(const std::shared_ptr<AccountListener> & listener) = 0;

    virtual void remove_listener(const std::shared_ptr<AccountListener> & listener) = 0;

    virtual void signup(const SignupMsg & info) = 0;

    virtual void login(const LoginMsg & info) = 0;

    virtual void logout(const TokenMsg & token) = 0;

    virtual void is_alive(const TokenMsg & token) = 0;
};

}  // namespace account
