// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#pragma once

#include <string>
#include <utility>

namespace account_djinni {

/** 登陆信息 */
struct LoginMsg final {
    std::string account;
    /** 账号，可以是用户名、手机号、email */
    std::string password;

    LoginMsg(std::string account_,
             std::string password_)
    : account(std::move(account_))
    , password(std::move(password_))
    {}
};

}  // namespace account_djinni
