// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#pragma once

#include <string>
#include <utility>

namespace account_djinni {

/** 注册信息 */
struct SignupMsg final {
    std::string username;
    /** 用户名，唯一存在 */
    std::string password;
    std::string phoneNumber;
    std::string email;
    std::string extra;

    SignupMsg(std::string username_,
              std::string password_,
              std::string phoneNumber_,
              std::string email_,
              std::string extra_)
    : username(std::move(username_))
    , password(std::move(password_))
    , phoneNumber(std::move(phoneNumber_))
    , email(std::move(email_))
    , extra(std::move(extra_))
    {}
};

}  // namespace account_djinni
