// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#pragma once

#include <cstdint>
#include <string>
#include <utility>

namespace account_djinni {

/** token信息 */
struct TokenMsg final {
    std::string token;
    int32_t expiration_time_sec;
    std::string username;

    TokenMsg(std::string token_,
             int32_t expiration_time_sec_,
             std::string username_)
    : token(std::move(token_))
    , expiration_time_sec(std::move(expiration_time_sec_))
    , username(std::move(username_))
    {}
};

}  // namespace account_djinni
