// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#pragma once

#include <string>
#include <utility>

namespace account {

/** token信息 */
struct TokenMsg final {
    std::string token;

    TokenMsg(std::string token_)
    : token(std::move(token_))
    {}
};

}  // namespace account
