// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#import "SCTokenMsg.h"
#import <Foundation/Foundation.h>

/** 所有账号相关信息，用于持久化到本地 */
@interface SCAccountInfo : NSObject
- (nonnull instancetype)initWithUsername:(nonnull NSString *)username
                                password:(nonnull NSString *)password
                             phoneNumber:(nonnull NSString *)phoneNumber
                                   email:(nonnull NSString *)email
                                   extra:(nonnull NSString *)extra
                                   token:(nonnull SCTokenMsg *)token;
+ (nonnull instancetype)accountInfoWithUsername:(nonnull NSString *)username
                                       password:(nonnull NSString *)password
                                    phoneNumber:(nonnull NSString *)phoneNumber
                                          email:(nonnull NSString *)email
                                          extra:(nonnull NSString *)extra
                                          token:(nonnull SCTokenMsg *)token;

@property (nonatomic, readonly, nonnull) NSString * username;

/** 用户名，唯一存在 */
@property (nonatomic, readonly, nonnull) NSString * password;

@property (nonatomic, readonly, nonnull) NSString * phoneNumber;

@property (nonatomic, readonly, nonnull) NSString * email;

@property (nonatomic, readonly, nonnull) NSString * extra;

@property (nonatomic, readonly, nonnull) SCTokenMsg * token;

@end
