// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#include "account_interface.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SCAccountInterface;

namespace djinni_generated {

class AccountInterface
{
public:
    using CppType = std::shared_ptr<::account::AccountInterface>;
    using CppOptType = std::shared_ptr<::account::AccountInterface>;
    using ObjcType = SCAccountInterface*;

    using Boxed = AccountInterface;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

