// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#import "SCLoginMsg.h"
#import "SCSignupMsg.h"
#import <Foundation/Foundation.h>
@class SCAccountInterface;
@protocol SCAccountListener;


@interface SCAccountInterface : NSObject

/** 单例 */
+ (nullable SCAccountInterface *)getInstance;

/** 初始化 */
- (void)init;

- (void)addListener:(nullable id<SCAccountListener>)listener;

- (void)removeListener:(nullable id<SCAccountListener>)listener;

- (void)signup:(nonnull SCSignupMsg *)info;

- (void)login:(nonnull SCLoginMsg *)info;

- (void)logout;

/** 手动发起服务器是否在线检查，会异步定时检查 */
- (void)isAlive;

/** 是否已经登录 */
- (BOOL)hasLogin;

@end
