// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#import "SCAccountInfo.h"
#include "account_info.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SCAccountInfo;

namespace djinni_generated {

struct AccountInfo
{
    using CppType = ::account_djinni::AccountInfo;
    using ObjcType = SCAccountInfo*;

    using Boxed = AccountInfo;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
