// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#import "SCAccountResp+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto AccountResp::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.code),
            ::djinni::String::toCpp(obj.msg),
            ::djinni::String::toCpp(obj.token),
            ::djinni::String::toCpp(obj.extra)};
}

auto AccountResp::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[SCAccountResp alloc] initWithCode:(::djinni::I32::fromCpp(cpp.code))
                                           msg:(::djinni::String::fromCpp(cpp.msg))
                                         token:(::djinni::String::fromCpp(cpp.token))
                                         extra:(::djinni::String::fromCpp(cpp.extra))];
}

}  // namespace djinni_generated
