// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#import "SCTokenMsg.h"
#import <Foundation/Foundation.h>

/** 账号结果返回 */
@interface SCAccountResp : NSObject
- (nonnull instancetype)initWithCode:(int32_t)code
                                 msg:(nonnull NSString *)msg
                            username:(nonnull NSString *)username
                               token:(nonnull SCTokenMsg *)token
                               extra:(nonnull NSString *)extra;
+ (nonnull instancetype)accountRespWithCode:(int32_t)code
                                        msg:(nonnull NSString *)msg
                                   username:(nonnull NSString *)username
                                      token:(nonnull SCTokenMsg *)token
                                      extra:(nonnull NSString *)extra;

@property (nonatomic, readonly) int32_t code;

/** 错误码 */
@property (nonatomic, readonly, nonnull) NSString * msg;

@property (nonatomic, readonly, nonnull) NSString * username;

/** 用户名，唯一存在 */
@property (nonatomic, readonly, nonnull) SCTokenMsg * token;

@property (nonatomic, readonly, nonnull) NSString * extra;

@end
