// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#import "SCAccountInfo.h"
#import "SCLoginMsg.h"
#import "SCSignupMsg.h"
#import <Foundation/Foundation.h>
@class SCAccountInterface;
@protocol SCAccountListener;


@interface SCAccountInterface : NSObject

/** 单例 */
+ (nullable SCAccountInterface *)getInstance;

/** 初始化 */
- (void)init;

/** 全局事件监听 */
- (void)addListener:(nullable id<SCAccountListener>)listener;

- (void)removeListener:(nullable id<SCAccountListener>)listener;

- (void)signup:(nonnull SCSignupMsg *)info
         seqId:(int32_t)seqId;

/** seqId 函数请求id，在account_listener里callback */
- (void)login:(nonnull SCLoginMsg *)info
        seqId:(int32_t)seqId;

- (void)logout:(int32_t)seqId;

- (nonnull SCAccountInfo *)getAccountInfo;

/** 手动发起服务器是否在线检查，会异步定时检查 */
- (void)isAlive;

/** 是否已经登录 */
- (BOOL)hasLogin;

@end
