// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#import "SCAccountInfo.h"
#import "SCAccountResp.h"
#import <Foundation/Foundation.h>


/** 全局事件监听 */
@protocol SCAccountListener

- (void)onSignupCallback:(nonnull SCAccountResp *)callback
                   seqId:(int32_t)seqId
                    info:(nonnull SCAccountInfo *)info;

- (void)onLoginCallback:(nonnull SCAccountResp *)callback
                  seqId:(int32_t)seqId
                   info:(nonnull SCAccountInfo *)info;

- (void)onLogoutCallback:(nonnull SCAccountResp *)callback
                   seqId:(int32_t)seqId;

- (void)onIsAliveCallback:(nonnull SCAccountResp *)callback;

@end
