// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#include "account_listener.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol SCAccountListener;

namespace djinni_generated {

class AccountListener
{
public:
    using CppType = std::shared_ptr<::account::AccountListener>;
    using CppOptType = std::shared_ptr<::account::AccountListener>;
    using ObjcType = id<SCAccountListener>;

    using Boxed = AccountListener;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

