// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#import "SCAccountResp.h"
#import <Foundation/Foundation.h>


@protocol SCAccountListener

- (void)onSignupCallback:(nonnull SCAccountResp *)callback;

- (void)onLoginCallback:(nonnull SCAccountResp *)callback;

- (void)onLogoutCallback:(nonnull SCAccountResp *)callback;

- (void)onIsAliveCallback:(nonnull SCAccountResp *)callback;

@end
