// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#import "SCLoginMsg.h"
#import "SCSignupMsg.h"
#import "SCTokenMsg.h"
#import <Foundation/Foundation.h>
@class SCAccountInterface;
@protocol SCAccountListener;


@interface SCAccountInterface : NSObject

+ (nullable SCAccountInterface *)getInstance;

- (void)addListener:(nullable id<SCAccountListener>)listener;

- (void)removeListener:(nullable id<SCAccountListener>)listener;

- (void)signup:(nonnull SCSignupMsg *)info;

- (void)login:(nonnull SCLoginMsg *)info;

- (void)logout:(nonnull SCTokenMsg *)token;

- (void)isAlive:(nonnull SCTokenMsg *)token;

@end
