// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#import "SCAccountInfo.h"


@implementation SCAccountInfo

- (nonnull instancetype)initWithUsername:(nonnull NSString *)username
                             phoneNumber:(nonnull NSString *)phoneNumber
                                   email:(nonnull NSString *)email
                                   extra:(nonnull NSString *)extra
                                   token:(nonnull SCTokenMsg *)token
                            refreshToken:(nonnull SCRefreshTokenMsg *)refreshToken
{
    if (self = [super init]) {
        _username = [username copy];
        _phoneNumber = [phoneNumber copy];
        _email = [email copy];
        _extra = [extra copy];
        _token = token;
        _refreshToken = refreshToken;
    }
    return self;
}

+ (nonnull instancetype)accountInfoWithUsername:(nonnull NSString *)username
                                    phoneNumber:(nonnull NSString *)phoneNumber
                                          email:(nonnull NSString *)email
                                          extra:(nonnull NSString *)extra
                                          token:(nonnull SCTokenMsg *)token
                                   refreshToken:(nonnull SCRefreshTokenMsg *)refreshToken
{
    return [(SCAccountInfo*)[self alloc] initWithUsername:username
                                              phoneNumber:phoneNumber
                                                    email:email
                                                    extra:extra
                                                    token:token
                                             refreshToken:refreshToken];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p username:%@ phoneNumber:%@ email:%@ extra:%@ token:%@ refreshToken:%@>", self.class, (void *)self, self.username, self.phoneNumber, self.email, self.extra, self.token, self.refreshToken];
}

@end
