// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#import <Foundation/Foundation.h>

/** 登陆信息 */
@interface SCLoginMsg : NSObject
- (nonnull instancetype)initWithAccount:(nonnull NSString *)account
                               password:(nonnull NSString *)password;
+ (nonnull instancetype)loginMsgWithAccount:(nonnull NSString *)account
                                   password:(nonnull NSString *)password;

@property (nonatomic, readonly, nonnull) NSString * account;

/** 账号，可以是用户名、手机号、email */
@property (nonatomic, readonly, nonnull) NSString * password;

@end
