// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#import "SCLoginMsg.h"
#include "login_msg.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SCLoginMsg;

namespace djinni_generated {

struct LoginMsg
{
    using CppType = ::account_djinni::LoginMsg;
    using ObjcType = SCLoginMsg*;

    using Boxed = LoginMsg;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
