// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#import "SCLoginMsg.h"


@implementation SCLoginMsg

- (nonnull instancetype)initWithAccount:(nonnull NSString *)account
                               password:(nonnull NSString *)password
{
    if (self = [super init]) {
        _account = [account copy];
        _password = [password copy];
    }
    return self;
}

+ (nonnull instancetype)loginMsgWithAccount:(nonnull NSString *)account
                                   password:(nonnull NSString *)password
{
    return [(SCLoginMsg*)[self alloc] initWithAccount:account
                                             password:password];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p account:%@ password:%@>", self.class, (void *)self, self.account, self.password];
}

@end
