// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#import "SCLoginMsg+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto LoginMsg::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.account),
            ::djinni::String::toCpp(obj.password)};
}

auto LoginMsg::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[SCLoginMsg alloc] initWithAccount:(::djinni::String::fromCpp(cpp.account))
                                      password:(::djinni::String::fromCpp(cpp.password))];
}

}  // namespace djinni_generated
