// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#import "SCRefreshTokenMsg+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto RefreshTokenMsg::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.refreshToken),
            ::djinni::I32::toCpp(obj.expirationTimeSec),
            ::djinni::String::toCpp(obj.username)};
}

auto RefreshTokenMsg::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[SCRefreshTokenMsg alloc] initWithRefreshToken:(::djinni::String::fromCpp(cpp.refresh_token))
                                         expirationTimeSec:(::djinni::I32::fromCpp(cpp.expiration_time_sec))
                                                  username:(::djinni::String::fromCpp(cpp.username))];
}

}  // namespace djinni_generated
