// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#import <Foundation/Foundation.h>

/** refresh_token信息 */
@interface SCRefreshTokenMsg : NSObject
- (nonnull instancetype)initWithRefreshToken:(nonnull NSString *)refreshToken
                           expirationTimeSec:(int32_t)expirationTimeSec
                                    username:(nonnull NSString *)username;
+ (nonnull instancetype)refreshTokenMsgWithRefreshToken:(nonnull NSString *)refreshToken
                                      expirationTimeSec:(int32_t)expirationTimeSec
                                               username:(nonnull NSString *)username;

@property (nonatomic, readonly, nonnull) NSString * refreshToken;

@property (nonatomic, readonly) int32_t expirationTimeSec;

@property (nonatomic, readonly, nonnull) NSString * username;

@end
