// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#import "SCRefreshTokenMsg.h"


@implementation SCRefreshTokenMsg

- (nonnull instancetype)initWithRefreshToken:(nonnull NSString *)refreshToken
                           expirationTimeSec:(int32_t)expirationTimeSec
                                    username:(nonnull NSString *)username
{
    if (self = [super init]) {
        _refreshToken = [refreshToken copy];
        _expirationTimeSec = expirationTimeSec;
        _username = [username copy];
    }
    return self;
}

+ (nonnull instancetype)refreshTokenMsgWithRefreshToken:(nonnull NSString *)refreshToken
                                      expirationTimeSec:(int32_t)expirationTimeSec
                                               username:(nonnull NSString *)username
{
    return [(SCRefreshTokenMsg*)[self alloc] initWithRefreshToken:refreshToken
                                                expirationTimeSec:expirationTimeSec
                                                         username:username];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p refreshToken:%@ expirationTimeSec:%@ username:%@>", self.class, (void *)self, self.refreshToken, @(self.expirationTimeSec), self.username];
}

@end
