// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#import "SCRefreshTokenMsg.h"
#include "refresh_token_msg.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SCRefreshTokenMsg;

namespace djinni_generated {

struct RefreshTokenMsg
{
    using CppType = ::account_djinni::RefreshTokenMsg;
    using ObjcType = SCRefreshTokenMsg*;

    using Boxed = RefreshTokenMsg;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
