// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#import "SCSignupMsg.h"
#include "signup_msg.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SCSignupMsg;

namespace djinni_generated {

struct SignupMsg
{
    using CppType = ::account_djinni::SignupMsg;
    using ObjcType = SCSignupMsg*;

    using Boxed = SignupMsg;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
