// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#import "SCSignupMsg.h"


@implementation SCSignupMsg

- (nonnull instancetype)initWithUsername:(nonnull NSString *)username
                                password:(nonnull NSString *)password
                             phoneNumber:(nonnull NSString *)phoneNumber
                                   email:(nonnull NSString *)email
                                   extra:(nonnull NSString *)extra
{
    if (self = [super init]) {
        _username = [username copy];
        _password = [password copy];
        _phoneNumber = [phoneNumber copy];
        _email = [email copy];
        _extra = [extra copy];
    }
    return self;
}

+ (nonnull instancetype)signupMsgWithUsername:(nonnull NSString *)username
                                     password:(nonnull NSString *)password
                                  phoneNumber:(nonnull NSString *)phoneNumber
                                        email:(nonnull NSString *)email
                                        extra:(nonnull NSString *)extra
{
    return [(SCSignupMsg*)[self alloc] initWithUsername:username
                                               password:password
                                            phoneNumber:phoneNumber
                                                  email:email
                                                  extra:extra];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p username:%@ password:%@ phoneNumber:%@ email:%@ extra:%@>", self.class, (void *)self, self.username, self.password, self.phoneNumber, self.email, self.extra];
}

@end
