// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#import "SCSignupMsg+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto SignupMsg::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.username),
            ::djinni::String::toCpp(obj.password),
            ::djinni::String::toCpp(obj.phoneNumber),
            ::djinni::String::toCpp(obj.email),
            ::djinni::String::toCpp(obj.extra)};
}

auto SignupMsg::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[SCSignupMsg alloc] initWithUsername:(::djinni::String::fromCpp(cpp.username))
                                        password:(::djinni::String::fromCpp(cpp.password))
                                     phoneNumber:(::djinni::String::fromCpp(cpp.phoneNumber))
                                           email:(::djinni::String::fromCpp(cpp.email))
                                           extra:(::djinni::String::fromCpp(cpp.extra))];
}

}  // namespace djinni_generated
