// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#import <Foundation/Foundation.h>

/** 注册信息 */
@interface SCSignupMsg : NSObject
- (nonnull instancetype)initWithUsername:(nonnull NSString *)username
                                password:(nonnull NSString *)password
                             phoneNumber:(nonnull NSString *)phoneNumber
                                   email:(nonnull NSString *)email
                                   extra:(nonnull NSString *)extra;
+ (nonnull instancetype)signupMsgWithUsername:(nonnull NSString *)username
                                     password:(nonnull NSString *)password
                                  phoneNumber:(nonnull NSString *)phoneNumber
                                        email:(nonnull NSString *)email
                                        extra:(nonnull NSString *)extra;

@property (nonatomic, readonly, nonnull) NSString * username;

/** 用户名，唯一存在 */
@property (nonatomic, readonly, nonnull) NSString * password;

@property (nonatomic, readonly, nonnull) NSString * phoneNumber;

@property (nonatomic, readonly, nonnull) NSString * email;

@property (nonatomic, readonly, nonnull) NSString * extra;

@end
