// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#import "SCTokenMsg.h"


@implementation SCTokenMsg

- (nonnull instancetype)initWithToken:(nonnull NSString *)token
{
    if (self = [super init]) {
        _token = [token copy];
    }
    return self;
}

+ (nonnull instancetype)tokenMsgWithToken:(nonnull NSString *)token
{
    return [(SCTokenMsg*)[self alloc] initWithToken:token];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p token:%@>", self.class, (void *)self, self.token];
}

@end
