// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#import "SCTokenMsg.h"
#include "token_msg.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SCTokenMsg;

namespace djinni_generated {

struct TokenMsg
{
    using CppType = ::account_djinni::TokenMsg;
    using ObjcType = SCTokenMsg*;

    using Boxed = TokenMsg;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
