// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#import <Foundation/Foundation.h>

/** token信息 */
@interface SCTokenMsg : NSObject
- (nonnull instancetype)initWithToken:(nonnull NSString *)token;
+ (nonnull instancetype)tokenMsgWithToken:(nonnull NSString *)token;

@property (nonatomic, readonly, nonnull) NSString * token;

@end
