// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from account.djinni

#import "SCTokenMsg+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto TokenMsg::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.token),
            ::djinni::I32::toCpp(obj.expirationTimeSec),
            ::djinni::String::toCpp(obj.username)};
}

auto TokenMsg::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[SCTokenMsg alloc] initWithToken:(::djinni::String::fromCpp(cpp.token))
                           expirationTimeSec:(::djinni::I32::fromCpp(cpp.expiration_time_sec))
                                    username:(::djinni::String::fromCpp(cpp.username))];
}

}  // namespace djinni_generated
